### ISSUE TITLE
ELK 6 support?

### ISSUE THREAD

**Issue by atbohmer** [StamusNetworks/KTS5#10]
Hello,
Migrating elasticsearch from 5.6 to 6 did not show major problems regarding already collected data via the SELKS setup on RedHat EL 7, but Kibana 6 fails. Are you planning a release of KTS5 (or maybe KTS6) which will work on ELK 6?
Kind regards,
Andre 

After stopping Kibana, removing the index .Kibana and starting Kibana, it works well. But after running the load.sh script it reports import errors and Kibana itself afterwards reports " Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant. "

Loading dashboard SN-STATS:
+ curl -H 'Content-Type: application/json' -XPUT http://127.0.0.1:9200/.kibana/dashboard/SN-STATS -d @dashboards/dashboard/SN-STATS.json
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [index-pattern, dashboard]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [index-pattern, dashboard]"},"status":400}+ echo

**Comment by pevma** [comment]
> On 17 Nov 2017, at 13:17, atbohmer <notifications@github.com> wrote:
> 
> Hello,
> Migrating elasticsearch from 5.6 to 6 did not show major problems regarding already collected data via the SELKS setup on RedHat EL 7, but Kibana 6 fails. Are you planning a release of KTS5 (or maybe KTS6) which will work on ELK 6?
> Kind regards,
> Andre
> 
> After stopping Kibana, removing the index .Kibana and starting Kibana, it works well. But after running the load.sh script it reports import errors and Kibana itself afterwards reports " Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant. "
> 

Does it work as expected if you use a dashboard reset from Scirius?

**Comment by atbohmer** [comment]
Sorry I use a custom setup on RedHat EL 7 without Scirius, only imported your very helpful dashboard. If I follow ELK instructions regarding updating Kibana from 5.6 to 6, most of the dashboards work like a charm. The load.sh however still fails, so I guess a fresh ELK6 will fail importing the dashboards. 
Is there a script or command I could use to produce the same as a dashboard reset from Scirius?

**Comment by pevma** [comment]
ok.
Yes ELK 6 just came out with a healthy amount of features and some backward compatibility breaking changes  - so we would need to make KTS6 i guess for that purpose.

**Comment by atbohmer** [comment]
Ok thanks, looking forward to KTS6 and 7 ;-)

**Comment by myrinx** [comment]
+1 on this. Just tried to load KTS on ELK6, and it breaks heavily. 

When is the KTS6 variant to be expected?

**Comment by foremandomai** [comment]
What needs to be done to make this work?

**Comment by pevma** [comment]
All of the visualizations and dashboards would need to be redone for ELK6.
I am currently starting to do that now. will update soon - end of next week I think.

**Comment by rsenden** [comment]
Any news on this? I have recently installed Suricata 4.0.5, and LogStash, ElasticSearch and Kibana versions 6.3.2 in customized Docker containers (tried to use the Amsterdam project, but this project seems to use some older product versions). 

I'm new to all of these products, so it would be nice to have some ready-to-use visualizations and dashboards in Kibana instead of having to figure out myself how to define these. 

At the moment I've just defined a single Geolocation Map visualization, and I'm using the Discover page to find specific events and their details.

**Comment by pevma** [comment]
Hi!
There was quite some bit of work done already. So we expect to have our SELKS 5 Beta out in 2-3 weeks time for some feedback!

**Comment by pevma** [comment]
KTS6 is here  - https://github.com/StamusNetworks/KTS6

Update -  https://github.com/StamusNetworks/KTS6/issues/1  
Seems our first feedback is positive on the new ELK6 compatible dashboards :) 
Please give it a try and let us know how it goes.
