### ISSUE TITLE
Mapping conflict

### ISSUE THREAD

**Issue by lapnd** [StamusNetworks/KTS5#5]
Hello,
I have just installed ELK 5.5.1 and try to import KTS5.
After running ./load.sh and login to Kibana I got message with patten "logstash-*"

Mapping conflict
A field is defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data.

The conflict filed is geoip.coordinates
The type of this field changes across indices. It is unavailable for many analysis functions. The indices per type are as follows:

Type | Index Names
-- | --
float | logstash-alert-2016.08.12-reindexed, logstash-alert-2017.07.05, logstash-alert-2017.07.12, logstash-alert-2017.07.12-reindexed, logstash-alert-2017.07.13, logstash-dns-2017.07.05, logstash-fileinfo-2016.08.12-reindexed, logstash-fileinfo-2017.07.05, logstash-fileinfo-2017.07.12, logstash-fileinfo-2017.07.12-reindexed, logstash-fileinfo-2017.07.13, logstash-flow-2017.07.05, logstash-flow-2017.07.12, logstash-flow-2017.07.12-reindexed, logstash-flow-2017.07.13, logstash-http-2017.07.05, logstash-http-2017.07.12, logstash-http-2017.07.12-reindexed, logstash-http-2017.07.13, logstash-smtp-2017.07.05, logstash-ssh-2017.07.05, logstash-tls-2017.07.05, logstash-tls-2017.07.12, logstash-tls-2017.07.12-reindexed, logstash-tls-2017.07.13
long | logstash-flow-2016.08.12-reindexed, logstash-http-2016.08.12-reindexed, logstash-tls-2016.08.12-reindexed

Could you please tell me how to fix this issue?
Thank you!

**Comment by pevma** [comment]
Seems you have done some reindexing of the data? Maybe you should try closing or deleting the old indices?

**Comment by vpiserchia** [comment]
Hello, I see that the conflict come from the index pattern definition, for example in the logstash-*.json I see:
{\"name\":\"geoip.coordinates\",\"type\":\"conflict\",\"count\":0,\"scripted\":false,\"searchable\":false,\"aggregatable\":false,\"readFromDocValues\":false,\"conflictDescriptions\":{\"float\":[\"logstash-alert-2016.08.12-reindexed\",\"logstash-alert-2017.07.05\",\"logstash-alert-2017.07.12\",\"logstash-alert-2017.07.12-reindexed\",\"logstash-alert-2017.07.13\",\"logstash-dns-2017.07.05\",\"logstash-fileinfo-2016.08.12-reindexed\",\"logstash-fileinfo-2017.07.05\",\"logstash-fileinfo-2017.07.12\",\"logstash-fileinfo-2017.07.12-reindexed\",\"logstash-fileinfo-2017.07.13\",\"logstash-flow-2017.07.05\",\"logstash-flow-2017.07.12\",\"logstash-flow-2017.07.12-reindexed\",\"logstash-flow-2017.07.13\",\"logstash-http-2017.07.05\",\"logstash-http-2017.07.12\",\"logstash-http-2017.07.12-reindexed\",\"logstash-http-2017.07.13\",\"logstash-smtp-2017.07.05\",\"logstash-ssh-2017.07.05\",\"logstash-tls-2017.07.05\",\"logstash-tls-2017.07.12\",\"logstash-tls-2017.07.12-reindexed\",\"logstash-tls-2017.07.13\"],\"long\":[\"logstash-flow-2016.08.12-reindexed\",\"logstash-http-2016.08.12-reindexed\",\"logstash-tls-2016.08.12-reindexed\"]}}

For a simple fix you can substitute the above with something like:

{\"name\":\"geoip.coordinates\",\"type\":\"float\",\"count\":0,\"scripted\":false,\"searchable\":false,\"aggregatable\":false,\"readFromDocValues\":false}

**Comment by pevma** [comment]
Found out that if you use [Scirius](https://github.com/StamusNetworks/scirius) (as part of [SELKS](https://github.com/StamusNetworks/SELKS) or stand alone ) when you reset the dashboards from within Scirius's web GUI - there are no issues. 

I have managed to pinpoint and alpha test a patch fix for the load script for the installs/imports that depend just on it. Will keep you posted.

**Comment by pevma** [comment]
Should be fixed by - https://github.com/StamusNetworks/KTS5/pull/11
