### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/KTS5#6]
WIth the latest version of kibana and using the KTS5 dashboards I am getting:

> No results found on a lot of visualizations. 

When I the field list they change to: 

> Could not locate that index-pattern-field (id: ...). 

I fixed this issue by changing the .raw entries to .keyword in the visualizations. 

This seems to have changed with ELK 5: https://www.elastic.co/guide/en/logstash/current/breaking-changes.html#_elasticsearch_output_index_template

**Comment by pevma** [comment]
Hi,

Not sure if you have done it - 
Did you use the template located here :
https://github.com/StamusNetworks/KTS5/tree/master/es-template

Thanks

**Comment by Eagleman7** [comment]
Yes I am using that template.

**Comment by pevma** [comment]
Which ELK stack versions do you have?

> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
5.5.2 is the latest stable version of ELK.

**Comment by pevma** [comment]
Are you using SELKS?

> -- 
> Regards,
> Peter Manev

**Comment by Eagleman7** [comment]
No, I am using this template on a clean ELK stack installation with no indices.

Imported with scirius or using the provided ./load.sh script, both have the same problems.

**Comment by pevma** [comment]
Ah ok.
In that case I can suggest if you could please have a look the way it is set up in SELKS and if it differs from your set up? Also check for errors in ``/var/log/logstash*``.

**Comment by Eagleman7** [comment]
My logstash and template file comes straight from the SELKS image, the only thing I changed in there is the type, SELKS > Suricata. The weirdest thing is that I didnt had this problem when I first setup my ELK stack, but now I keep getting this error, maybe they enforced the .keyword with the newest version of ELK?

Anyway I fixed this issue by changing all .raw to .keyword on all files inside the index-pattern and visualizations folder.

**Comment by pevma** [comment]
yes indeed - that should fix the issue - however it is not needed in SELKS (which currently uses 5.5.2 ELK stack) - so I keep wondering what is different.

**Comment by severgun** [comment]
Have same issue.
I downloaded SELKS distro image, mount filesystem.squashfs and copied configs for logstash and suricata.
And... raw fields have no data.

CentOS 7.3
Suricata 4.0
ELK 5.5.2 installed from official RPMs

**Comment by pevma** [comment]
Yes that is to be expected as `raw` fields are there for backward compatibility if you had ES 2.x and upgraded to ES5 - that way both will be displayed. If you start clean on ES5 then you should switch to  `keyword` only by - 

> find path/to//KTS5/dashboards/ -type f -exec sed -i -e 's/.raw/.keyword/g' {} ;

I have updated the [Readme](https://github.com/StamusNetworks/KTS5#how-to-use) instructions.
Thanks for the report!
